### PR TITLE
libelement/LMNT: compiler optimisations, change to ASSIGNCxx instructions

### PR DESCRIPTION
**Pull request by Esvandiary**
**libelement LMNT Compiler Optimisations/Features**
- Generates much better code for `if` statements where both result paths are scalar constants (e.g. casting to bool, and other related operations)
- Adds options to restrict what LMNT features the compiled code will contain (e.g. looping, dynamic indexing)
- Generates much better code for `select` statements where all result paths are scalar constants in a contiguous block (e.g. access into a big list of constants) if dynamic indexing is allowed

**Condition-based assignment instruction changes**
The `ASSIGNCxx` set of instructions assign one of two values to a target stack location, depending on the result of the last comparison instruction. Previously these values were defined as `int16` constant values encoded as part of the instruction; this was very compact codesize-wise but was extremely restrictive in terms of what you could do with it.
This PR changes the instructions to instead take stack locations as inputs, allowing any constants or prior computation to be used for the inputs.

The libelement LMNT compiler is updated to take advantage of this change as long as both the inputs are scalar constants (as used in the `if` change). This _should_ in theory extend to also work for scalar results of prior operations, but I want to think about that change a lot more before adding it, as done badly it could lead to unnecessary computation compiling both sides of a branch.

### CODE REVIEW

**Comment by Zephilinox** [comment]
awesome :) there's a lot I don't understand about LMNT and the JIT but from what I could see it all looked good and made sense. the dynamic indexing will help a lot, and it's nice to see the option to disable for loops now :)

one question I did have though is why someone would want to turn off dynamic indexing. I assume there is a downside?

**Comment by Zephilinox** [comment]
your favourite CI check is failing :)

**Comment by Esvandiary** [comment]
> awesome :) there's a lot I don't understand about LMNT and the JIT but from what I could see it all looked good and made sense. the dynamic indexing will help a lot, and it's nice to see the option to disable for loops now :)
Yeah the JIT code will always be the most difficult to read :smile: I ran through the test suite with the changes and it seems fine.

> one question I did have though is why someone would want to turn off dynamic indexing. I assume there is a downside?
Essentially I just want to have flags to allow/disallow each of the "could fail at runtime" scenarios (which are basically just looping, dynamic indexing, and external calls which the compiler has no support for anyway). I don't think it'd get turned off most of the time.

> your favourite CI check is failing :)
Enjoy the ridiculous beast of a reformatting commit as I changed some settings and broke other things in the codebase :joy:
Although it did find a bug-ish in one of the test files, there was a missing comma in a `TEST_CASE` definition :smile:

**Comment by Zephilinox** [comment]
haha cool. I didn't appreciate dynamic indexing could fail, but of course you can go outside of the bounds :b what happens then, nothing good I'm guessing?

the mac OS check is failing randomly again, ignore that 🙄 

aw I'm glad the formatting check wasn't a huge pain in the ass this time, don't worry that it was mixed with the fixes :b

**Review by Zephilinox — APPROVED** [review]

**Comment by Esvandiary** [comment]
> haha cool. I didn't appreciate dynamic indexing could fail, but of course you can go outside of the bounds :b what happens then, nothing good I'm guessing?

Yeah it'd cause the function to fail (`lmnt_execute` will return an error of some sort, probably `ACCESS_VIOLATION` at a guess). I did consider just saying that it'd clamp the index to be in bounds so it can't fail, but that felt like it could just end up hiding problems you actually need to fix.

**Pull request merged**
